### ISSUE TITLE
 Error: unhealthy cluster - https://localhost:2379

### ISSUE THREAD

**Issue by hernad** [cgruver/okd4-single-node-cluster#3]
Hi, my bootstrap node reports this error:  

[root@okd4-snc-bootstrap ~]# journalctl -b -f -u bootkube.service

<pre>
...
Jul 01 16:27:29 okd4-snc-bootstrap.snc.test bootkube.sh[674]: {"level":"warn","ts":"2020-07-01T16:27:29.381Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-9f885c4d-609f-444a-beab-393ba59f3c08/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:2379: connect: connection refused\""}
Jul 01 16:27:29 okd4-snc-bootstrap.snc.test bootkube.sh[674]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Jul 01 16:27:29 okd4-snc-bootstrap.snc.test bootkube.sh[674]: Error: unhealthy cluster
<pre>

**Comment by hernad** [comment]
DNS setup:

<pre>
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-16.P2.el7_8.6 <<>> axfr @192.168.168.10 snc.test
; (1 server found)
;; global options: +cmd
snc.test.               10800   IN      SOA     dc1.sa.out.ba. root.sa.out.ba. 18 28800 7200 604800 3600
snc.test.               900     IN      NS      ns.snc.test.
api.okd4-snc.snc.test.  900     IN      A       192.168.168.164
api.okd4-snc.snc.test.  900     IN      A       192.168.168.165
_etcd-server-ssl._tcp.okd4-snc.snc.test. 900 IN SRV 0 10 2380 etcd-0.okd4-snc.snc.test.
okd4-snc-host.snc.test. 900     IN      A       192.168.168.160
api-int.okd4-snc.snc.test. 900  IN      A       192.168.168.164
api-int.okd4-snc.snc.test. 900  IN      A       192.168.168.165
*.apps.okd4-snc.snc.test. 900   IN      CNAME   okd4-snc-master.snc.test.
okd4-snc-bootstrap.snc.test. 900 IN     A       192.168.168.164
ns.snc.test.            900     IN      A       192.168.168.10
etcd-0.okd4-snc.snc.test. 900   IN      A       192.168.168.165
okd4-snc-master.snc.test. 900   IN      A       192.168.168.165
snc.test.               10800   IN      SOA     dc1.sa.out.ba. root.sa.out.ba. 18 28800 7200 604800 3600

</pre>

**Comment by hernad** [comment]
[root@hp-144 okd4-snc]# cat ~/bin/setSncEnv.sh

<pre>
export SNC_DOMAIN=snc.test
export SNC_HOST=192.168.168.160
#export SNC_NAMESERVER=${SNC_HOST}
export SNC_NAMESERVER=192.168.168.10
export SNC_NETMASK=255.255.255.0
export SNC_GATEWAY=192.168.168.254
export INSTALL_HOST_IP=${SNC_HOST}
export INSTALL_ROOT=/usr/share/nginx/html/install
export INSTALL_URL=http://${SNC_HOST}/install
export OKD4_SNC_PATH=/root/okd4-snc
export OKD_REGISTRY=quay.io/openshift/okd
export OKD_RELEASE=4.4.0-0.okd-2020-05-23-055148-beta5
</pre>

**Comment by hernad** [comment]
[root@hp-144 okd4-snc]# cat install-config-snc.yaml
```
apiVersion: v1
baseDomain: snc.test
metadata:
  name: okd4-snc
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.100.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: ssh-rsa AAAABetc etc etc root@hp-144
```
